# Generated by Django 5.1.1 on 2024-10-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=100)),
                ('phone_number', models.IntegerField(verbose_name=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
