# Generated by Django 5.1.1 on 2024-10-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_crud_date_of_birth_alter_crud_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
