# Generated by Django 5.1.1 on 2024-10-17 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_publish_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='publisher',
            new_name='pub',
        ),
    ]
