# Generated by Django 5.1.1 on 2024-10-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0013_students_cours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='stds',
            new_name='stdns',
        ),
    ]
