# Generated by Django 5.1.1 on 2024-10-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0014_rename_stds_cours_stdns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='stdns',
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
