# Generated by Django 5.1.1 on 2024-10-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0017_hotel_gust'),
    ]

    operations = [
        migrations.CreateModel(
            name='userm',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
