# Generated by Django 5.1.1 on 2024-10-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0018_userm'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
            ],
        ),
    ]
