# Generated by Django 5.1.1 on 2024-11-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0022_uss'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='image/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
