# Generated by Django 5.1.1 on 2024-11-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0024_alter_img_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='img',
            new_name='imga',
        ),
    ]
